const details = {
  "How a watch keeps time.": "In a mechanical watch, stored energy travels through a train of tiny gears before reaching an escapement, which releases it in controlled beats. The balance wheel oscillates back and forth and sets that rhythm. Quartz follows a different route: a battery powers a crystal that vibrates at a very stable frequency, and electronics convert those vibrations into one-second steps. This is why the seconds hand often moves smoothly on a mechanical watch and jumps on quartz. Understanding the engine helps you choose for the right reason: mechanical is about craft and interaction; quartz is about ease and dependable precision. Neither choice is automatically more refined than the other.",
  "Mechanical, automatic or quartz?": "A hand-wound mechanical watch asks you to wind it regularly, creating a small daily ritual. An automatic has the same traditional architecture but adds a rotor that winds while you move; if it sits unused, it will eventually stop and need setting again. Quartz is powered by a battery and normally requires very little attention between battery changes. Think about your routine rather than status: someone who changes watches often may enjoy quartz, while someone who wears one piece daily may love an automatic. The right movement is the one that makes ownership enjoyable, not the one that wins an abstract debate.",
  "What specifications matter.": "Start with the details that change everyday ownership. Case diameter and lug-to-lug tell you how the watch may sit on the wrist; thickness affects whether it fits under a cuff. Sapphire crystal resists everyday scratches better than mineral glass, while water resistance must be matched to actual use. Movement type determines accuracy, interaction and future maintenance. Finally, look at warranty, returns and the seller’s location, especially when buying in Canada. A strong specification sheet is not a trophy list: it should answer practical questions about fit, durability and support. Compare the exact reference, because names within a collection can hide important differences.",
  "Water resistance, without the confusion.": "Water resistance is tested in controlled conditions, not a promise that every situation is identical. A watch rated for casual splashes should not be treated like a swim watch; a model intended for water still needs its crown closed and its seals maintained. Hot showers, steam rooms and sudden temperature changes can stress seals, so a high number on the dial is not permission to ignore care. If you swim or dive, use a watch designed for it and have its water resistance checked when servicing. When in doubt, follow the manufacturer’s specific manual. It is much cheaper to prevent moisture damage than to repair it.",
  "Finding the right fit.": "Try to judge a watch from several angles, not only from a front-facing photograph. Lug-to-lug length is often more important than diameter because it determines how much of the wrist the case occupies. Thickness affects balance, especially on smaller wrists or under a shirt cuff. Curved lugs, bracelet integration and strap thickness can make the same diameter wear very differently. There is no universal correct size; confidence comes from proportion and comfort. If possible, measure a watch you already enjoy and use that as your reference point. A watch should sit centered, feel stable and leave enough room for natural wrist movement.",
  "Care from day one.": "Good care begins with simple habits. Rinse or wipe a water-ready steel watch after sweat or salt exposure, then dry it with a soft cloth. Keep leather away from repeated soaking and allow it to rest between wears. Avoid setting a date during the movement’s restricted period if the manual warns against it, and do not expose a watch to severe shocks simply because it feels solid. Store it somewhere dry and protected from casual knocks. For automatic watches, normal wearing is enough; do not overthink daily winding. These routines preserve comfort, appearance and reliable function without turning ownership into a chore.",
  "What the crown does.": "The crown is the watch’s main control point, so patience matters. On a simple watch, one position may wind it and another may set the time. On a watch with date or GMT functions, additional positions may set those features separately. If the crown screws down, first unscrew it gently and later press it in while turning to secure it; cross-threading can damage the tube. Never force a crown, especially if it feels gritty or refuses to engage. Check the manual for your exact reference before using quick-set functions. A few careful seconds at the crown protects the movement and water resistance.",
  "Power reserve, in plain language.": "Power reserve measures stored running time, not accuracy or prestige. A 38-hour reserve can be perfectly practical for a watch worn daily, while a 70-hour reserve is convenient if you rotate between several watches over a weekend. Manual watches need winding to replenish their reserve; automatics build reserve through wear and sometimes hand winding. When a mechanical watch stops, it has not necessarily failed—it may simply be out of energy. Set it carefully after winding and allow it to run. Treat the published number as a guide rather than an exact stopwatch result, since use and movement condition influence it.",
  "Crystal: mineral, sapphire or acrylic?": "The crystal is the transparent surface over the dial, and its material shapes both durability and character. Sapphire is extremely resistant to everyday scratching, although a hard impact can still chip it. Mineral glass is less scratch resistant but is widely used and often economical to replace. Acrylic is light, warm-looking and common on vintage-inspired watches; it picks up marks more easily, but shallow scratches can sometimes be polished. Choose based on how you live with the watch rather than a hierarchy. For a daily piece, sapphire is reassuring; for a heritage design, acrylic may be part of the appeal.",
  "Date windows and calendar care.": "A date display is useful, but it adds a mechanism that needs respectful handling. Many mechanical movements begin changing the date late in the evening and finish after midnight. During that period, quick-setting the date can place stress on gears, depending on the calibre. The safest habit is to move the hands to a neutral daytime position before using a quick-set function, then consult the manufacturer’s instructions for your exact watch. If you own several watches, accept that a date may need correction after a month with fewer than 31 days. Convenience is valuable; forcing a calendar is not.",
  "Why lume matters.": "Lume is a coating that absorbs light and glows in darkness. It is most useful when you need to read time quickly in a cinema, on a flight, during an evening walk or in water. Brightness depends on the material, its application and how much light it received beforehand, so a dramatic product photograph does not tell the full story. Divers and field watches often prioritize large luminous markers, while refined dress watches may use minimal lume or none at all. Consider it a functional design choice. If night legibility matters to you, look at real reviews and photographs, not just a specification line.",
  "Bracelet basics.": "Bracelet fit should be deliberate but comfortable. It should not slide freely up and down the arm, yet it must leave room for the wrist to expand slightly through the day. Links can often be removed, while a micro-adjustment at the clasp refines the final fit. Pay attention to taper: a bracelet that narrows toward the clasp often feels more elegant and balanced. Solid construction is reassuring, but comfort, flexibility and a clean clasp matter more than weight alone. If you buy online, confirm whether sizing service, spare links and returns are available before ordering.",
  "Reading the caseback.": "The caseback can provide the first pieces of a watch’s identity. You may find a reference number, serial number, movement designation, water-resistance rating, material marks and manufacturing information. These markings help locate manuals, confirm compatible straps and communicate accurately with a service center. They are not, by themselves, a complete authentication guarantee: counterfeits can copy markings, and vintage watches may have replacement parts. Use them as a starting point, then compare the entire watch against reliable sources. Photograph the caseback and keep the image with your purchase records. It becomes useful whenever you need service or insurance.",
  "Your first watch rotation.": "A rotation should solve different needs rather than chase quantity. One everyday watch with clean proportions may cover work, dinners and weekends. A second could bring water resistance, a lighter case, a more formal dial or a colour that changes the mood. Before adding another, ask which occasions your current watch genuinely does not serve. This keeps purchases intentional and lets you learn your taste over time. It also makes maintenance simpler and prevents a drawer full of near-duplicates. A small rotation can feel more luxurious when every piece earns its wrist time.",
  "Dress, field, diver or chronograph?": "These categories are useful shorthand, not strict rules. A dress watch is usually slim and restrained, often pairing well with tailoring. A field watch favours clear numerals and robustness. A diver uses a rotating timing bezel and strong water resistance, while a chronograph adds a stopwatch display. You can wear any of them in many situations, but the category reveals the designer’s priorities. Start with your real schedule: office, travel, outdoors, formal events or weekends. The most convincing style choice is a watch whose function and appearance make sense in your own life, rather than one selected only for its label.",
  "What a brand can signal.": "A brand may bring a recognizable design language, a known service network, a certain movement strategy or a particular history. Those factors can be meaningful, but they do not make every model equally good. Compare the actual reference: finishing, crystal, movement, fit, warranty and seller support. Ask whether the price is paying for functionality, craft, heritage, scarcity or simply visibility. Brands also change over time, so old assumptions can be misleading. A well-informed buyer respects reputation without becoming captive to it. The logo should begin your research, not end it.",
  "Complications, explained simply.": "A complication adds information or a function beyond basic time display. A date is the most common; a GMT tracks another time zone; a chronograph measures intervals; a moonphase follows lunar cycles. More complications can make a watch fascinating and useful, but they also add controls, thickness and possible service complexity. Choose one because you will enjoy or use it, not merely because it makes the dial busier. A clean three-hand watch can be more elegant and legible than a crowded multi-function piece. The best complication is one that supports your habits and does not make the watch harder to live with.",
  "Steel, titanium, gold and ceramic.": "Materials affect weight, temperature, scratches and visual presence. Stainless steel is versatile, familiar and easy to match. Titanium is noticeably lighter and often comfortable for larger cases, although its surface can develop marks differently. Gold brings warmth and density, but its softness asks for more care. Ceramic is extremely scratch resistant and can offer a dramatic polished or matte look, though a sharp impact can damage it. None is automatically superior. Think about your skin sensitivity, lifestyle, preferred weight and wardrobe. Material should reinforce the purpose of the watch, not merely inflate its specification sheet.",
  "Straps change the whole watch.": "A strap is the fastest way to change a watch’s personality. Leather generally feels more formal and softens a sporty case. Rubber suits water and active use, while a textile strap can make a watch relaxed and light. A bracelet adds a more architectural, all-season look. Before buying an alternative, confirm lug width, spring-bar type and case clearance. Good straps should fit cleanly without bulging or leaving obvious gaps. Consider colour, texture and clasp as part of the design. One thoughtfully chosen strap can make a familiar watch feel newly relevant without requiring another purchase.",
  "Dial anatomy and legibility.": "A dial works when information is easy to absorb at a glance. Hands should contrast with the dial, indices should be clear, and the minute track should support rather than crowd the display. Date windows, subdials and logos all compete for space, so proportion matters. High-polish hands can look refined but may reflect light; matte surfaces can improve legibility. Before buying online, view the watch in multiple lighting conditions. A beautiful dial that is difficult to read can become frustrating in daily use. Good design is not minimalism for its own sake—it is clarity with character.",
  "What a bezel can do.": "A bezel is the ring surrounding the crystal. On a diver, a unidirectional rotating bezel tracks elapsed minutes and is designed to avoid accidentally extending a timing reading. A GMT-style bezel can help read a second time zone, while tachymeter scales relate to chronograph use. Many bezels are fixed and purely visual, yet they still affect how large, sporty or refined a watch feels. Try turning a functional bezel before buying if possible: action, grip and alignment are part of quality. Understand its purpose so you are not paying for a feature you will never enjoy.",
  "Understanding accuracy.": "Accuracy should be judged by movement type and use. Quartz watches typically lose or gain very little time over a month; mechanical watches may gain or lose seconds each day within the maker’s stated tolerance. Position, temperature and level of wind can affect a mechanical result. If you love engineering and a smooth seconds hand, a small daily variation may be part of the experience. If you need exact time with minimal attention, quartz is hard to beat. A sudden major change in performance, however, can signal a need for service. Learn the expected range before assuming something is wrong.",
  "How to read a reference number.": "Collection names are helpful, but the reference number is the precise identity of a watch. It distinguishes dial colours, case materials, bracelet options and sometimes movement variations that share the same family name. Use it when comparing sellers, searching manuals or checking manufacturer specifications. Be cautious with product pages that use only a shortened model name; ask for the complete reference before buying. Keep it with your own records after purchase. This small sequence of letters and numbers makes research more exact, especially when prices and listings vary. It is the language that connects a watch to its real specifications.",
  "Buying online with discipline.": "Online shopping is convenient when you slow down at the right moments. Confirm the exact reference, the condition, the seller’s identity, return period, warranty validity and whether duties or taxes are included in the final price. Save screenshots of the listing and written promises. Be cautious with stock images that do not clearly show the actual item when buying pre-owned. A good listing answers normal questions without pressure. If the seller avoids the reference number, provides inconsistent photos or insists on an unusual payment method, walk away. Patience is cheaper than resolving a bad purchase after delivery.",
  "How a watch wears with style.": "Styling begins with proportion and restraint. A slim, simple watch often works with tailoring because it passes under a cuff and does not compete with the outfit. Sportier cases, textured dials and rubber straps can make sense with casual clothing or travel. Metal tone, dial colour and surface finish all influence whether a watch reads quiet, modern or expressive. Do not treat rules as rigid: an intentional contrast can look excellent. The goal is coherence. Choose a watch that supports the setting and reflects your own taste rather than trying to make one piece perform every possible role.",
  "Choose with context.": "A collector’s comparison starts with the complete object, not hype. Put the reference, current price, dimensions, movement, condition, warranty and seller terms side by side. Then ask how it fits your existing watches and your real calendar. A slightly less famous model may be the better choice if it wears better, is easier to service and suits your style more naturally. Avoid making a decision from one dramatic image or one claim about future value. Context turns collecting into a long-term practice of judgment. The more deliberately you compare, the fewer impulsive purchases you need to regret.",
  "Service is part of ownership.": "Every watch eventually needs attention, although the schedule depends on movement, use and condition. Quartz usually needs a battery and periodic seal checks; mechanical watches may need cleaning, lubrication and regulation by a qualified professional. Ask where service is available in Canada, what the warranty covers and whether the movement has dependable parts support. Keep invoices and service records with the watch. They document care and help future owners understand its history. Do not wait for a serious failure if you notice moisture, erratic timekeeping or a stiff crown. Routine service is an ownership cost, not a surprise punishment.",
  "Condition, completeness and provenance.": "Condition means more than whether a watch looks clean. Examine case shape, dial originality, hand corrosion, bracelet stretch, crystal damage and evidence of poor repair. Completeness can include box, papers, spare links, receipts and service records; these support the story but should never distract from the watch itself. Provenance is the chain of information showing where it came from and how it was cared for. The strongest purchase combines clear condition, honest documentation and a seller willing to answer normal questions. Be especially cautious when a rare story is used to excuse vague photographs or missing details.",
  "Value is not the same as resale.": "Value begins with what you receive today: design you enjoy, comfortable fit, appropriate durability, service access and a price you can afford without strain. Resale is a separate, unpredictable market influenced by fashion, supply, condition and brand demand. Some watches hold value well, but no normal purchase should be presented as a guarantee. If future liquidity matters, buy a known reference in good condition from a reliable source and keep all documentation. Still, the most satisfying collection is usually built around use and personal conviction. A watch that stays on your wrist often delivers more value than one purchased only as an asset.",
  "Building a focused collection.": "A focused collection tells a clear story. You might explore one brand, a single era, different watch functions or a carefully chosen wardrobe of everyday, sport and dress pieces. Set a budget and a rule for each addition: it should add a new experience, not repeat an existing watch with a slightly different dial. Photograph your collection and write down what you actually wear; patterns quickly appear. This reflection protects you from buying out of temporary excitement. Focus does not mean being rigid. It means knowing why a watch belongs, so each new piece feels connected rather than random.",
  "Vintage: charm and responsibility.": "Vintage watches reward patience because their condition varies more than modern watches. Water resistance may no longer be reliable, luminous material may have aged, and replacement parts may affect originality. A serviced vintage movement can be excellent, but service must be performed with sensitivity to preserve important details. Learn the correct dial, handset, caseback and movement for the reference before buying. Ask about moisture history and work performed. Vintage is not only about age or patina; it is about understanding what has survived and what has changed. Buy from a source that welcomes careful questions and provides clear pictures.",
  "Polishing changes a case.": "Polishing removes a small amount of metal to reduce visible scratches. Done carefully, it can refresh a watch; done repeatedly or aggressively, it can round off sharp lines, soften original brushing and change the proportions of the case. This matters particularly with vintage watches or models known for crisp geometry. Look at the lugs, bezel edges and transition between polished and brushed surfaces under good light. Do not assume every mark should disappear. Honest wear can be preferable to a case that has lost its original character. If you commission work, choose a specialist and discuss preservation before cosmetic perfection.",
  "Movement calibres matter.": "The calibre is the specific movement inside a watch, and it influences experience beyond the dial. It can determine power reserve, beat rate, date function, thickness, service access and expected accuracy. Some calibres are widely used and easy for independent watchmakers to service; others are more specialized. Learn the calibre name when researching a serious purchase, then read the manufacturer’s manual and warranty terms. Do not obsess over it at the expense of fit and design, but do not ignore it either. A watch is a complete object, and the movement explains much of what happens after the first exciting week.",
  "Insurance and secure storage.": "As your collection grows, create a simple record for every watch: reference, serial, photographs, purchase date, price, receipt and service history. Store digital copies separately from the watch itself. Ask an insurance professional whether your existing policy covers jewellery and watches away from home, and understand any appraisal requirements. At home, keep watches dry, protected from direct sun and away from strong magnets or casual access. A safe or secure cabinet can be sensible for valuable pieces, but daily practical security matters too. Documentation and careful storage reduce stress and make any future claim or sale much easier.",
  "When to walk away.": "The ability to decline a watch is a collector’s advantage. Walk away if the reference does not match the photos, if a seller avoids straightforward questions, if the story changes, or if the urgency feels manufactured. Unusually low prices demand unusually clear explanations, not blind optimism. For pre-owned pieces, poor images, missing caseback views and vague service claims are reasons to pause. There will always be another watch, often a better one. Keep your budget and standards visible before you start browsing. Patience protects both your money and the pleasure of discovering a piece you can genuinely trust."
};
window.academyDetails = details;

document.querySelectorAll(".lesson").forEach((lesson) => {
  const title = lesson.querySelector("h2")?.textContent.trim();
  const summary = lesson.querySelector("p");
  if (!title || !summary || !details[title]) return;
  const expanded = document.createElement("p");
  expanded.textContent = details[title];
  const practice = document.createElement("p");
  practice.innerHTML = "<b>Practical application:</b> use this lesson while evaluating a real reference: read the official manual, write down the relevant details, and compare them with your intended use. Revisit those notes after a few weeks of wear; that is when a specification becomes genuine value.";
  lesson.insertBefore(expanded, lesson.querySelector(".cta"));
  lesson.insertBefore(practice, lesson.querySelector(".cta"));
  const heading = lesson.querySelector("h2");
  if (heading && !heading.querySelector("a")) {
    const link = document.createElement("a");
    link.href = `lesson.html?topic=${encodeURIComponent(title)}`;
    link.textContent = title;
    link.style.color = "inherit";
    link.style.textDecoration = "none";
    heading.replaceChildren(link);
  }
});
